name: build
on: [push]
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: lhci-pokedex
        run: |
          curl https://webhook.mattycakes.ca/hooks/pokedex-documentation-master?token=${{ secrets.LHCI_WEBHOOK }}