name: Lighthouse Test
on:
  workflow_run:
    workflows: [Gatsby Build Webook]
    types:
      - completed
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install && npm install -g @lhci/cli
      - run: npm run build
      - run: lhci autorun