name: Lighthouse Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install && npm install -g @lhci/cli
      - run: npm run build
      - run: lhci autorun
      - run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{"text": "**LHCI TESTING COMPLETE ON GITHUB CI/CD**"}' https://mm.mattycakes.ca/hooks/${{ secrets.MATTERMOST_SECRET }}