name: Prettier Format
# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,css,scss}
      - name: cURL Mattermost Webhook
        run: |
          curl -i -X POST -H 'Content-Type: application/json' -d '{"text": "**PRETTIER WRITE COMPLETE ON GITHUB CI/CD**"}' https://mm.mattycakes.ca/hooks/${{ secrets.MATTERMOST_SECRET }}